- name: Installing snmp traps packages
  apt:
    name:
    - snmpd
    - snmp
    - libsnmp-dev
    - snmptrapd
    state: latest
    cache_valid_time: yes
  become: true

# TODO Setting up firewall to allow traps listening

- name: Download Zabbix trap receiver script
  ansible.builtin.get_url:
    url: "https://git.zabbix.com/projects/ZBX/repos/zabbix/raw/misc/snmptrap/zabbix_trap_receiver.pl"
    dest: "/usr/local/bin/zabbix_trap_receiver.pl"
    mode: "0755"
  become: true

- name: Setting log file location for Traps perl
  ansible.builtin.lineinfile:
    path: /usr/local/bin/zabbix_trap_receiver.pl
    regexp: '^\$SNMPTrapperFile'
    line: "$SNMPTrapperFile = '/tmp/zabbix_snmp_traps.log';"
  become: true

- name: Setting log file location for Traps
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^SNMPTrapperFile'
    line: "SNMPTrapperFile=/tmp/zabbix_snmp_traps.log"
  become: true

- name: Ensure SNMP trapper is enabled
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^#?\s*StartSNMPTrapper\s*=\s*0\s*$'
    replace: 'StartSNMPTrapper=1'
  become: true

- name: Add Zabbix trap receiver configuration to snmptrapd.conf
  ansible.builtin.blockinfile:
    path: /etc/snmp/snmptrapd.conf
    marker: "# {mark} ANSIBLE ZABBIX TRAP RECEIVER"
    block: |
      authCommunity log,execute,net public
      perl do "/usr/local/bin/zabbix_trap_receiver.pl";
  become: true

- name: Ensure snmptrapd is enabled and restarted
  ansible.builtin.service:
    name: snmptrapd
    enabled: true
    state: restarted
  become: true

- name: Ensure snmptrapd listens on UDP/162 (Debian-style default opts)
  ansible.builtin.lineinfile:
    path: /etc/default/snmptrapd
    create: yes
    regexp: '^SNMPTRAPDOPTS='
    line: 'SNMPTRAPDOPTS="-n -Lo -c /etc/snmp/snmptrapd.conf"'
  become: true
  notify: restart snmptrapd

- name: Ensure snmptrapd listens on UDP/162 (Debian-style default opts)
  ansible.builtin.lineinfile:
    path: /etc/default/snmptrapd
    create: yes
    regexp: '^SNMPTRAPDOPTS='
    line: 'SNMPTRAPDOPTS="-n -Lo -c /etc/snmp/snmptrapd.conf"'
  become: true
  notify: restart snmptrapd