---
- name: Create virtual IP resource
  command: >
    pcs resource create virtual-ip
    ocf:heartbeat:IPaddr2
    ip={{ cluster_vip }}
    cidr_netmask={{ cluster_vip_cidr }}
    nic={{ cluster_vip_nic }}
    op monitor interval=1s timeout=2s
    op start  timeout=5s
    op stop   timeout=5s
  run_once: true
  delegate_to: "{{ groups['companion'][0] }}"

- name: Create companion service resource
  command: >
    pcs resource create companion-service
    systemd:companion
    op monitor interval=1s  timeout=2s
    op start   timeout=10s
    op stop    timeout=15s
  run_once: true
  delegate_to: "{{ groups['companion'][0] }}"

- name: Create resource group
  command: pcs resource group add companion_group virtual-ip companion-service
  run_once: true
  delegate_to: "{{ groups['companion'][0] }}"

- name: Set companion service failover meta attributes
  command: >
    pcs resource meta companion-service
    migration-threshold=1
    failure-timeout=30s
  run_once: true
  delegate_to: "{{ groups['companion'][0] }}"

- name: Set default resource timeouts (rsc_defaults)
  command: >
    pcs resource defaults update
    migration-threshold=1
  run_once: true
  delegate_to: "{{ groups['companion'][0] }}"